server:
  port: 3011
spring:
  datasource:
    url: jdbc:mysql://39.104.137.220:3306/logistics_db
    username: shixun
    password: shixun
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: customer-service-center
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.182.6:8848


mybatis:
  mapper-locations: classpath:cn/neusoft/mapper/*Mapper.xml
